version: "3"
services:
  usermanager:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: usermanager
    restart: always
    depends_on:
      - auth_db
    ports: 
      - 8082:8082
  auth_db:
    image: mongo
    restart: always
    container_name: auth_db
    ports:
      - 27017:27017
    volumes:
      - ./database/mongo-entrypoint/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_USERNAME: user
      MONGO_PASSWORD: secret

  mongo_seed:
    image: mongo
    container_name: mongo_seed
    links:
      - auth_db
    volumes:
      - ./database/mongoseed:/mongoseed
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command:
      /mongoseed/import.sh
    
