version: "3"
services:
  usermanager:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: usermanager
    restart: always
    depends_on:
      - auth_db
    ports: 
      - 8082:8082
    networks:
      - lib_network


  auth_db:
    image: mongo
    restart: always
    container_name: auth_db
    ports:
      - 27017:27017
    volumes:
      - ./database/mongo-entrypoint/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_USERNAME: user
      MONGO_PASSWORD: secret
    networks:
      - lib_network

  mongoseed:
    image: mongo
    depends_on:
      - auth_db
    restart: "no"
    volumes:
      - ./database/mongoseed/:/mongoseed/
  #  entrypoint: [ "bash", "-c", "sleep 10 && mongo --host mongo:27017 --eval 'rs.initiate()'"]      
    
networks:
  lib_network:
    name: lib_network